Mysubj='Computer Science'
print(Mysubj[0:len(Mysubj)])
print(Mysubj[len(Mysubj)-1])
print(2* Mysubj)
print(Mysubj[::-2])
print(Mysubj[:3] + Mysubj[3:])
print(Mysubj.swapcase())
print(Mysubj.startswith('Comp'))
print(Mysubj.isalpha())
print(Mysubj.upper())
print(Mysubj.count('put'))
print(Mysubj.find('Sci'))
print(Mysubj.index('Science'))
print(Mysubj.replace('Science','Engineering'))
print(Mysubj.split(' '))
